In [2]:
import torch
torch.cuda.is_available()
import numpy as np
import torch.nn as nn
log = np.log2(1).astype(np.int32)
import math

In [3]:
BOOTSTRAP_EVERY = 8
DENOISE_TIMESTEPS = 128
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
CLASS_DROPOUT_PROB = 1.0
NUM_CLASSES = 1
BATCH_SIZE = 64
current_batch_size = 64

images = torch.randn(BATCH_SIZE, 3, 64, 64).to(DEVICE)
labels = torch.randint(0, NUM_CLASSES, (BATCH_SIZE,)).to(DEVICE)
print(f"Images shape: {images.shape}, Labels shape: {labels.shape}")

Images shape: torch.Size([64, 3, 64, 64]), Labels shape: torch.Size([64])


In [4]:
torch.device("cuda" if torch.cuda.is_available() else "cpu")

device(type='cuda')

In [11]:
a = {'test':["d"]}

if 'test' in a:
    a['test'].append('b')

a["te"] = ["as"]
b= a

In [48]:
4096*256
32768/4096


8.0

In [4]:
import torch
d = torch.randn((8*4096,1))
def split_tensor_n(tensor, n):
    split_size = tensor.shape[0] // n
    return [tensor[i*split_size:(i+1)*split_size] for i in range(n)]

n = 4
splits = split_tensor_n(d, n)
for idx, part in enumerate(splits):
    print(f"Split {idx} shape: {part.shape}")

Split 0 shape: torch.Size([8192, 1])
Split 1 shape: torch.Size([8192, 1])
Split 2 shape: torch.Size([8192, 1])
Split 3 shape: torch.Size([8192, 1])


In [3]:
import torch
# a = torch.stack(splits, dim=0)
x = torch.tensor([1.0, 2.0, -3.0])
if (x < 0).any():
    print("There are negative values in the tensor.")
# for i in a:
#     print(i.shape)
#     print(a[0] == i)    


There are negative values in the tensor.


In [ ]:
import torch
d = torch.randn((8*4096,1))
for i in d:
    print(i.shape)
def actor_loss2(old_neglogp, neglogp, adv, e_clip):
    old_neg = old_neglogp.view(-1)
    new_neg = neglogp.view(-1)
    advantage = adv.view(-1)

    # compute logprobs from neglogp
    old_logp = -old_neg
    new_logp = -new_neg

    ratio = torch.exp(new_logp - old_logp)  # p_new / p_old

    surr1 = ratio * advantage
    surr2 = torch.clamp(ratio, 1.0 - e_clip, 1.0 + e_clip) * advantage

    # PPO loss is negative of clipped surrogate (we want to maximize surrogate)
    loss = -torch.min(surr1, surr2)
    print(loss.shape)
    # return per-sample loss (keep dims consistent)
    return loss.view(-1, 1)

actor_loss2(d,d,d,0.2).shape

torch.Size([4096])


torch.Size([4096, 1])

dataset transpose test

In [ ]:
import torch
import time
a  = torch.zeros([87])
b  = torch.zeros([4096,1])
c  = torch.ones([4096,1])
f  = torch.ones([4096,1])*2
# c = torch.zeros((32,4096)+a.shape)
# c.shape
d = torch.rand_like(b)

# for i in range(c.):
#     c[i]
start_time = time.time()
lst = [torch.randn(4096,1) for _ in range(8)]  # (1,2) 모양 8개 생성
# lst = [torch.ones(2,1)*i for i in range(8)]  # (1,2) 모양 8개 생성
# for i in range(c.shape[0]):
#     c[i] = d
print("Time taken:", time.time() - start_time)
# for i in range(c.shape[0]):
#     b = torch.stack([d,b],dim=0)
result = torch.stack(lst, dim=0)             # (8,1,2)로 쌓임
print("Time taken:", time.time() - start_time)
d = torch.stack((b,c,f))
# print(result.shape)  # torch.Size([8, 1, 2])
# dic = {'a':[b,d]}
# dic['a'] = torch.stack(dic['a'],dim=0)
# dic['a'].shape
print(f"d shape: {d.shape},, d tans: {d.transpose(0,1)[0]}")
si = result.shape
# print(result[0])
# print(result)
# print(result.shape)
result[0]
result1 = result.transpose(0,1).reshape(si[0]*si[1],*si[2:])
result2 = result.transpose(0,1).reshape(-1,*si[2:])
print(result1[0])
print(result2[0],result1[0]==result2[0])
for i in range(4):
    print(result[32768*i:32768*(i+1)].shape)
# torch.transpose()


Time taken: 0.0002570152282714844
Time taken: 0.0004885196685791016
d shape: torch.Size([3, 4096, 1]),, d tans: tensor([[0.],
        [1.],
        [2.]])
tensor([[[ 1.5457],
         [-0.2376],
         [ 0.9051],
         ...,
         [-0.7562],
         [-0.0993],
         [-0.2117]],

        [[-0.0991],
         [-1.7937],
         [ 1.2755],
         ...,
         [ 0.4598],
         [-1.1647],
         [-0.0739]],

        [[-1.6033],
         [-1.6810],
         [-0.5727],
         ...,
         [-1.2869],
         [-0.2517],
         [-1.4079]],

        ...,

        [[ 0.9722],
         [ 1.2388],
         [ 0.3819],
         ...,
         [ 0.3158],
         [ 0.5915],
         [-0.1988]],

        [[-0.9326],
         [-0.0985],
         [-1.1302],
         ...,
         [-1.9054],
         [-0.9601],
         [ 0.8808]],

        [[ 0.2014],
         [-0.1467],
         [-0.8937],
         ...,
         [-1.1303],
         [ 1.3742],
         [ 0.0539]]])
torch.Size([8, 

In [12]:
import torch
if 0.any():
    print('sd')
print(torch.randn((3,1,1)))
if torch.randn((3,1,1)).any():
    print('sd')

SyntaxError: invalid decimal literal (2094664333.py, line 2)

In [ ]:
def create_targets(images, labels, model):
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
    model.eval()

    current_batch_size = images.shape[0]

    FORCE_T = -1
    FORCE_DT = -1

    # 1. create step sizes dt
    bootstrap_batch_size = current_batch_size // BOOTSTRAP_EVERY #=8
    log2_sections = int(math.log2(DENOISE_TIMESTEPS))
    # print(f"log2_sections: {log2_sections}")
    # print(f"bootstrap_batch_size: {bootstrap_batch_size}")

    dt_base = torch.repeat_interleave(log2_sections - 1 - torch.arange(log2_sections), bootstrap_batch_size // log2_sections)
    # print(f"dt_base: {dt_base}")

    dt_base = torch.cat([dt_base, torch.zeros(bootstrap_batch_size-dt_base.shape[0],)])
    # print(f"dt_base: {dt_base}")


    dt = 1 / (2 ** (dt_base.to(DEVICE))) # [1, 1/2, 1/8, 1/16, 1/32]
    # print(f"dt: {dt}")

    dt_base_bootstrap = dt_base + 1
    dt_bootstrap = dt / 2 # [0.0078125 0.015625 0.03125 0.0625 0.125 0.25 0.5 0.5]
    # print(f"dt_bootstrap: {dt_bootstrap}")

    # 2. sample timesteps t
    dt_sections = 2**dt_base

    # print(f"dt_sections: {dt_sections}")

    t = torch.cat([
        torch.randint(low=0, high=int(val.item()), size=(1,)).float()
        for val in dt_sections
        ]).to(model.device)
    
    # print(f"t[randint]: {t}")
    t = t / dt_sections
    # print(f"t[normalized]: {t}")
    
    force_t_vec = torch.ones(bootstrap_batch_size, dtype=torch.float32).to(model.device) * FORCE_T
    t = torch.where(force_t_vec != -1, force_t_vec, t).to(model.device)
    t_full = t[:, None, None, None]

    # print(f"t_full: {t_full}")

    # 3. generate bootstrap targets:
    x_1 = images[:bootstrap_batch_size]
    x_0 = torch.randn_like(x_1)

    # get dx at timestep t
    x_t = (1 - (1-1e-5) * t_full)*x_0 + t_full*x_1

    bst_labels = labels[:bootstrap_batch_size]


    with torch.no_grad():
        v_b1 = model(x_t, t, dt_base_bootstrap, bst_labels)

    t2 = t + dt_bootstrap
    x_t2 = x_t + dt_bootstrap[:, None, None, None] * v_b1
    x_t2 = torch.clip(x_t2, -4, 4)
    
    with torch.no_grad():
        v_b2 = model(x_t2, t2, dt_base_bootstrap, bst_labels)

    v_target = (v_b1 + v_b2) / 2

    v_target = torch.clip(v_target, -4, 4)
    
    bst_v = v_target
    bst_dt = dt_base
    bst_t = t
    bst_xt = x_t
    bst_l = bst_labels

    # 4. generate flow-matching targets

    labels_dropout = torch.bernoulli(torch.full(labels.shape, CLASS_DROPOUT_PROB)).to(model.device)
    labels_dropped = torch.where(labels_dropout.bool(), NUM_CLASSES, labels)

    # sample t(normalized)
    t = torch.randint(low=0, high=DENOISE_TIMESTEPS, size=(images.shape[0],), dtype=torch.float32)
    t /= DENOISE_TIMESTEPS
    t_full = t[:, None, None, None]

    # print(f"t_full: {t_full}")

    # sample flow pairs x_t, v_t
    x_0 = torch.randn_like(images).to(model.device)
    x_1 = images
    x_t = (1 - (1 - 1e-5) * t_full) * x_0 + t_full * x_1
    v_t = x_1 - (1 - 1e-5) * x_0

    dt_flow = int(math.log2(DENOISE_TIMESTEPS))
    dt_base = (torch.ones(images.shape[0], dtype=torch.int32) * dt_flow).to(model.device)

    # 5. merge flow and bootstrap
    bst_size = current_batch_size // BOOTSTRAP_EVERY
    bst_size_data = current_batch_size - bst_size

    # print(f"bst_size: {bst_size}")
    # print(f"bst_size_data: {bst_size_data}")

    x_t = torch.cat([bst_xt, x_t[:bst_size_data]], dim=0)
    t = torch.cat([bst_t, t[:bst_size_data]], dim=0)

    dt_base = torch.cat([bst_dt, dt_base[:bst_size_data]], dim=0)
    v_t = torch.cat([bst_v, v_t[:bst_size_data]], dim=0)
    labels_dropped = torch.cat([bst_l, labels_dropped[:bst_size_data]], dim=0)

    return x_t, v_t, t, dt_base, labels_dropped

In [9]:
bootstrap_batch_size = current_batch_size // BOOTSTRAP_EVERY #=8
log2_sections = int(math.log2(DENOISE_TIMESTEPS))
print(f"log2_sections: {log2_sections}")
print(f"bootstrap_batch_size: {bootstrap_batch_size}")

dt_base = torch.repeat_interleave(log2_sections - 1 - torch.arange(log2_sections), bootstrap_batch_size // log2_sections)
print(f"dt_base: {dt_base}, shape: {dt_base.shape}")

dt_base = torch.cat([dt_base, torch.zeros(bootstrap_batch_size-dt_base.shape[0],)])
print(f"dt_base: {dt_base}")



dt = 1 / (2 ** (dt_base.to(DEVICE))) # [1, 1/2, 1/8, 1/16, 1/32]
print(f"dt: {dt}")

dt_base_bootstrap = dt_base + 1
dt_bootstrap = dt / 2 # [0.0078125 0.015625 0.03125 0.0625 0.125 0.25 0.5 0.5]
print(f"dt_bootstrap: {dt_bootstrap}")

# 2. sample timesteps t
dt_sections = 2**dt_base.to(DEVICE)
print(f"dt_sections: {dt_sections}")    
t = torch.cat([
        torch.randint(low=0, high=int(val.item()), size=(1,)).float()
        for val in dt_sections
        ]).to(DEVICE)
t = t / dt_sections
print(f"t: {t}")
t_full = t[:, None, None, None]
x_1 = images[:bootstrap_batch_size]
x_0 = torch.randn_like(x_1)

x_t = (1 - (1-1e-5) * t_full)*x_0 + t_full*x_1
bst_labels = labels[:bootstrap_batch_size]

t2 = t + dt_bootstrap
x_t2 = x_t + dt_bootstrap[:, None, None, None]
print(f"t2: {t2}")
t = torch.randint(low=0, high=DENOISE_TIMESTEPS, size=(images.shape[0],), dtype=torch.float32)
# print(f"t: {t}, size: {t.size()}")
t /= DENOISE_TIMESTEPS
# print(f"t: {t}, size: {t.size()}")
dt_flow = int(math.log2(DENOISE_TIMESTEPS))
dt_base = (torch.ones(images.shape[0], dtype=torch.int32) * dt_flow).to(DEVICE)
print(f"dt_base: {dt_base}, size: {dt_base.size()}")

log2_sections: 7
bootstrap_batch_size: 8
dt_base: tensor([6, 5, 4, 3, 2, 1, 0]), shape: torch.Size([7])
dt_base: tensor([6., 5., 4., 3., 2., 1., 0., 0.])
dt: tensor([0.0156, 0.0312, 0.0625, 0.1250, 0.2500, 0.5000, 1.0000, 1.0000],
       device='cuda:0')
dt_bootstrap: tensor([0.0078, 0.0156, 0.0312, 0.0625, 0.1250, 0.2500, 0.5000, 0.5000],
       device='cuda:0')
dt_sections: tensor([64., 32., 16.,  8.,  4.,  2.,  1.,  1.], device='cuda:0')
t: tensor([0.1250, 0.8125, 0.6875, 0.5000, 0.7500, 0.0000, 0.0000, 0.0000],
       device='cuda:0')
t2: tensor([0.1328, 0.8281, 0.7188, 0.5625, 0.8750, 0.2500, 0.5000, 0.5000],
       device='cuda:0')
dt_base: tensor([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7], device='cuda:0',
       dtype=torch.int32), size: torch.Size([64])


In [3]:
x_1 = images[:bootstrap_batch_size]
x_0 = torch.randn_like(x_1)

    # get dx at timestep t
x_t = (1 - (1-1e-5) * t_full)*x_0 + t_full*x_1

NameError: name 'images' is not defined

In [4]:
print(torch.arange(log2_sections))
print(dt_base)
dt = 1 / (2 ** (dt_base))
dt_base_bootstrap = dt_base + 1
dt_bootstrap = dt / 2 
dt_sections = 2**dt_base
t = torch.cat([
        torch.randint(low=0, high=int(val.item()), size=(1,)).float()
        for val in dt_sections
        ]).to(DEVICE)
print("dt_sections",dt_sections)
t = t / dt_sections
print("t", t)
t_full = t[:, None, None, None]
print("t_full", t_full.size())
images = torch.randn(BATCH_SIZE, 3, 64, 64).to(DEVICE)
print("images", images.size())
t2 = t + dt_bootstrap
t = torch.randint(low=0, high=DENOISE_TIMESTEPS, size=(images.shape[0],), dtype=torch.float32).to(DEVICE)
print("t rand", t.size())
t /= DENOISE_TIMESTEPS
t_full = t[:, None, None, None]
images[:bootstrap_batch_size].size()

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([6., 5., 4., 3., 2., 1., 0., 0.], device='cuda:0')
dt_sections tensor([64., 32., 16.,  8.,  4.,  2.,  1.,  1.], device='cuda:0')
t tensor([0.8750, 0.3750, 0.1875, 0.0000, 0.0000, 0.5000, 0.0000, 0.0000],
       device='cuda:0')
t_full torch.Size([8, 1, 1, 1])
images torch.Size([64, 3, 64, 64])
t rand torch.Size([64])


torch.Size([8, 3, 64, 64])

In [ ]:
bst_v = v_target
bst_dt = dt_base
bst_t = t
bst_xt = x_t
bst_l = bst_labels

# sample flow pairs x_t, v_t
x_0 = torch.randn_like(images).to(model.device)
x_1 = images
x_t = (1 - (1 - 1e-5) * t_full) * x_0 + t_full * x_1
v_t = x_1 - (1 - 1e-5) * x_0

dt_flow = int(math.log2(DENOISE_TIMESTEPS))
dt_base = (torch.ones(images.shape[0], dtype=torch.int32) * dt_flow).to(model.device)

# 5. merge flow and bootstrap
bst_size = current_batch_size // BOOTSTRAP_EVERY
bst_size_data = current_batch_size - bst_size

# print(f"bst_size: {bst_size}")
# print(f"bst_size_data: {bst_size_data}")

x_t = torch.cat([bst_xt, x_t[:bst_size_data]], dim=0)
t = torch.cat([bst_t, t[:bst_size_data]], dim=0)

dt_base = torch.cat([bst_dt, dt_base[:bst_size_data]], dim=0)
v_t = torch.cat([bst_v, v_t[:bst_size_data]], dim=0)
labels_dropped = torch.cat([bst_l, labels_dropped[:bst_size_data]], dim=0)

x_0 torch.Size([64, 3, 64, 64])
